import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Componets/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <Navbar></Navbar>
        <main className="min-h-[700px]">{children}</main>
        <footer className="text-center bg-cyan-700">
          Awsome Footer
        </footer>
      </body>
    </html>
  );
}
